historypath : "http://hl7.org/fhir/us/core/history.html"
summaries: true #true if want custom profile summaries in summary tab
diff2: false # true if want to show intermediate differentials
build: ci  # choice of ci|ballot|version
example_types:
  - Patient
  - AllergyIntolerance
  - CarePlan
  - CareTeam
  - Condition
  - Device
  - DiagnosticReport
  - DocumentReference
  - Encounter
  - Goal
  - Immunization
  - Location
  - Medication
  - MedicationStatement
  - MedicationRequest
  - Observation
  - Organization
  - Practitioner
  - PractitionerRole
  - Procedure
  - Bundle
conformance_types:
  - StructureDefinition
  - ValueSet
  - CodeSystem
  - ConceptMap
  - CapabilityStatement
  - OperationDefinition
  - SearchParameter
  - ImplementationGuide
resource_types:
  - Account
  - ActivityDefinition
  - AdverseEvent
  - AllergyIntolerance
  - Appointment
  - AppointmentResponse
  - AuditEvent
  - Basic
  - Binary
  - BiologicallyDerivedProduct
  - BodyStructure
  - Bundle
  - CapabilityStatement
  - CarePlan
  - CareTeam
  - CatalogEntry
  - ChargeItem
  - ChargeItemDefinition
  - Claim
  - ClaimResponse
  - ClinicalImpression
  - CodeSystem
  - Communication
  - CommunicationRequest
  - CompartmentDefinition
  - Composition
  - ConceptMap
  - Condition
  - Consent
  - Contract
  - Coverage
  - CoverageEligibilityRequest
  - CoverageEligibilityResponse
  - DetectedIssue
  - Device
  - DeviceDefinition
  - DeviceMetric
  - DeviceRequest
  - DeviceUseStatement
  - DiagnosticReport
  - DocumentManifest
  - DocumentReference
  - DomainResource
  - EffectEvidenceSynthesis
  - Encounter
  - Endpoint
  - EnrollmentRequest
  - EnrollmentResponse
  - EpisodeOfCare
  - EventDefinition
  - Evidence
  - EvidenceVariable
  - ExampleScenario
  - ExplanationOfBenefit
  - FamilyMemberHistory
  - Flag
  - Goal
  - GraphDefinition
  - Group
  - GuidanceResponse
  - HealthcareService
  - ImagingStudy
  - Immunization
  - ImmunizationEvaluation
  - ImmunizationRecommendation
  - ImplementationGuide
  - InsurancePlan
  - Invoice
  - ItemInstance
  - Library
  - Linkage
  - List
  - Location
  - Measure
  - MeasureReport
  - Media
  - Medication
  - MedicationAdministration
  - MedicationDispense
  - MedicationKnowledge
  - MedicationRequest
  - MedicationStatement
  - MedicinalProduct
  - MedicinalProductAuthorization
  - MedicinalProductContraindication
  - MedicinalProductIndication
  - MedicinalProductIngredient
  - MedicinalProductInteraction
  - MedicinalProductManufactured
  - MedicinalProductPackaged
  - MedicinalProductPharmaceutical
  - MedicinalProductUndesirableEffect
  - MessageDefinition
  - MessageHeader
  - NamingSystem
  - NutritionOrder
  - Observation
  - ObservationDefinition
  - OperationDefinition
  - OperationOutcome
  - Organization
  - OrganizationAffiliation
  - Parameters
  - Patient
  - PaymentNotice
  - PaymentReconciliation
  - Person
  - PlanDefinition
  - Practitioner
  - PractitionerRole
  - Procedure
  - ProcessRequest
  - ProcessResponse
  - Provenance
  - Questionnaire
  - QuestionnaireResponse
  - RelatedPerson
  - RequestGroup
  - ResearchDefinition
  - ResearchElementDefinition
  - ResearchStudy
  - ResearchSubject
  - Resource
  - RiskAssessment
  - RiskEvidenceSynthesis
  - Schedule
  - SearchParameter
  - Sequence
  - ServiceRequest
  - Slot
  - Specimen
  - SpecimenDefinition
  - StructureDefinition
  - StructureMap
  - Subscription
  - Substance
  - SubstanceNucleicAcid
  - SubstancePolymer
  - SubstanceProtein
  - SubstanceReferenceInformation
  - SubstanceSourceMaterial
  - SubstanceSpecification
  - SupplyDelivery
  - SupplyRequest
  - Task
  - TerminologyCapabilities
  - TestReport
  - TestScript
  - UserSession
  - ValueSet
  - VerificationResult
  - VisionPrescription
